/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Promotion = {
  _id: string;
  _type: "promotion";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  status?: "active" | "paused";
  poster?: ImageWithAlt;
  badge?: string;
  summary?: string;
  offerCode?: string;
  validityLabel?: string;
  startsAt?: string;
  endsAt?: string;
  showOnHomepage?: boolean;
  callToAction?: Link;
  terms?: string;
  displayOrder?: number;
};

export type Link = {
  _type: "link";
  label?: string;
  href?: string;
  openInNewTab?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  name?: string;
  source?: string;
  rating?: number;
  displayOrder?: number;
  published?: boolean;
};

export type LegalPage = {
  _id: string;
  _type: "legalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pageKey?: "privacy" | "cookie" | "returns";
  title?: string;
  summary?: string;
  lastUpdated?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: ImageWithAlt;
  noIndex?: boolean;
};

export type FaqItem = {
  _id: string;
  _type: "faqItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: string;
  category?: string;
  displayOrder?: number;
  published?: boolean;
};

export type MarketingPage = {
  _id: string;
  _type: "marketingPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pageKey?:
    "home" | "restaurant" | "hall" | "story" | "story-calicut" | "payments";
  title?: string;
  eyebrow?: string;
  heroHeading?: string;
  heroText?: string;
  heroImage?: ImageWithAlt;
  heroPrimaryLink?: Link;
  heroSecondaryLink?: Link;
  sections?: Array<
    | ({
        _key: string;
      } & ContentSection)
    | ({
        _key: string;
      } & CallToAction)
  >;
  seo?: Seo;
};

export type MenuItemReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "menuItem";
};

export type MenuPage = {
  _id: string;
  _type: "menuPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  headingLineOne?: string;
  headingLineTwo?: string;
  introduction?: string;
  journeyLinkLabel?: string;
  manifestEyebrow?: string;
  manifestHeading?: string;
  manifestIntroduction?: string;
  dietaryNotice?: string;
  alcoholNotice?: string;
  voyageStops?: Array<{
    dish?: MenuItemReference;
    area?: string;
    port?: string;
    region?: string;
    coordinates?: string;
    yearLabel?: string;
    courseLabel?: string;
    image?: ImageWithAlt;
    description?: string;
    _key: string;
  }>;
  seo?: Seo;
};

export type MenuCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "menuCategory";
};

export type MenuItem = {
  _id: string;
  _type: "menuItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  sourceKey?: string;
  category?: MenuCategoryReference;
  description?: string;
  subheading?: string;
  image?: ImageWithAlt;
  pricePence?: number;
  priceLabel?: string;
  hidePrice?: boolean;
  isAlcoholic?: boolean;
  isVegetarian?: boolean;
  isVegan?: boolean;
  dietaryReviewStatus?: "confirmed" | "needs-review";
  dietaryNotes?: string;
  allergens?: Array<string>;
  allergenNotes?: string;
  spiceLevel?: "none" | "gentle" | "warm" | "medium" | "hot" | "aromatic";
  available?: boolean;
  onlineOrdering?: boolean;
  featured?: boolean;
  displayOrder?: number;
};

export type MenuCategory = {
  _id: string;
  _type: "menuCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  shortTitle?: string;
  eyebrow?: string;
  description?: string;
  orderRank?: number;
  published?: boolean;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  restaurantName?: string;
  legalName?: string;
  shortDescription?: string;
  description?: string;
  logo?: ImageWithAlt;
  lightLogo?: ImageWithAlt;
  favicon?: ImageWithAlt;
  siteUrl?: string;
  phone?: string;
  email?: string;
  reservationEmail?: string;
  address?: {
    streetAddress?: string;
    locality?: string;
    region?: string;
    postalCode?: string;
    country?: string;
  };
  coordinates?: {
    latitude?: number;
    longitude?: number;
  };
  mapUrl?: string;
  openingHours?: Array<{
    days?: string;
    hours?: string;
    _key: string;
  }>;
  socialLinks?: Array<{
    platform?: string;
    url?: string;
    _key: string;
  }>;
  primaryNavigation?: Array<
    {
      _key: string;
    } & Link
  >;
  footerNavigation?: Array<
    {
      _key: string;
    } & Link
  >;
  announcement?: string;
  copyrightText?: string;
  defaultSeo?: Seo;
};

export type ContentSection = {
  _type: "contentSection";
  internalName?: string;
  eyebrow?: string;
  heading?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: ImageWithAlt;
  secondaryImage?: ImageWithAlt;
  links?: Array<
    {
      _key: string;
    } & Link
  >;
  shortLabel?: string;
  note?: string;
  theme?: "dark" | "light" | "green" | "copper";
};

export type CallToAction = {
  _type: "callToAction";
  eyebrow?: string;
  heading?: string;
  text?: string;
  primaryLink?: Link;
  secondaryLink?: Link;
  image?: ImageWithAlt;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Promotion
  | Link
  | SanityImageAssetReference
  | ImageWithAlt
  | Slug
  | Testimonial
  | LegalPage
  | Seo
  | FaqItem
  | MarketingPage
  | MenuItemReference
  | MenuPage
  | MenuCategoryReference
  | MenuItem
  | MenuCategory
  | SiteSettings
  | ContentSection
  | CallToAction
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../sanity/lib/admin-content.ts
// Variable: adminContentOverviewQuery
// Query: {  "menuItems": *[_type == "menuItem"] | order(category->orderRank asc, displayOrder asc, name asc) {    _id,    name,    "category": category->title,    "categorySlug": category->slug.current,    pricePence,    "available": coalesce(available, true),    "onlineOrdering": coalesce(onlineOrdering, true),    "featured": coalesce(featured, false),    "isAlcoholic": coalesce(isAlcoholic, false),    "updatedAt": _updatedAt  },  "promotions": *[_type == "promotion"] | order(displayOrder asc, _updatedAt desc) {    _id,    title,    "status": coalesce(status, "paused"),    "showOnHomepage": coalesce(showOnHomepage, false),    startsAt,    endsAt,    "updatedAt": _updatedAt,    poster {alt, "url": asset->url}  },  "pages": *[_type in ["marketingPage", "legalPage"]] | order(_type asc, pageKey asc) {    _id,    _type,    title,    pageKey,    "updatedAt": _updatedAt  },  "categoryCount": count(*[_type == "menuCategory"]),  "faqCount": count(*[_type == "faqItem"]),  "testimonialCount": count(*[_type == "testimonial"]),  "hasMenuPage": defined(*[_id == "menuPage"][0]._id),  "hasSiteSettings": defined(*[_id == "siteSettings"][0]._id)}
export type AdminContentOverviewQueryResult = {
  menuItems: Array<{
    _id: string;
    name: string | null;
    category: string | null;
    categorySlug: string | null;
    pricePence: number | null;
    available: boolean | true;
    onlineOrdering: boolean | true;
    featured: boolean | false;
    isAlcoholic: boolean | false;
    updatedAt: string;
  }>;
  promotions: Array<{
    _id: string;
    title: string | null;
    status: "active" | "paused";
    showOnHomepage: boolean | false;
    startsAt: string | null;
    endsAt: string | null;
    updatedAt: string;
    poster: {
      alt: string | null;
      url: string | null;
    } | null;
  }>;
  pages: Array<
    | {
        _id: string;
        _type: "legalPage";
        title: string | null;
        pageKey: "cookie" | "privacy" | "returns" | null;
        updatedAt: string;
      }
    | {
        _id: string;
        _type: "marketingPage";
        title: string | null;
        pageKey:
          | "hall"
          | "home"
          | "payments"
          | "restaurant"
          | "story-calicut"
          | "story"
          | null;
        updatedAt: string;
      }
  >;
  categoryCount: number;
  faqCount: number;
  testimonialCount: number;
  hasMenuPage: false | true;
  hasSiteSettings: false | true;
};

// Source: ../sanity/lib/queries.ts
// Variable: menuContentQuery
// Query: {  "categories": *[_type == "menuCategory" && published != false] | order(orderRank asc) {    "slug": slug.current,    title,    "note": coalesce(shortTitle, title),    "description": coalesce(description, ""),    orderRank  },  "items": *[_type == "menuItem"] | order(category->orderRank asc, displayOrder asc, name asc) {    "id": coalesce(sourceKey, _id),    "category": category->slug.current,    name,    "description": coalesce(description, ""),    subheading,    pricePence,    priceLabel,    hidePrice,    isAlcoholic,    isVegetarian,    isVegan,    dietaryReviewStatus,    "allergens": coalesce(allergens, []),    spiceLevel,    available,    onlineOrdering,    featured,    displayOrder,    image {      alt,      caption,      "url": asset->url,      "dimensions": asset->metadata.dimensions    }  },  "page": *[_id == "menuPage"][0] {    eyebrow,    headingLineOne,    headingLineTwo,    introduction,    journeyLinkLabel,    manifestEyebrow,    manifestHeading,    manifestIntroduction,    dietaryNotice,    alcoholNotice,    voyageStops[] {      _key,      "itemId": coalesce(dish->sourceKey, dish->_id),      "area": coalesce(area, port),      region,      coordinates,      "year": yearLabel,      "course": courseLabel,      description,      image {        alt,        "url": asset->url,        "dimensions": asset->metadata.dimensions      }    },    seo  }}
export type MenuContentQueryResult = {
  categories: Array<{
    slug: string | null;
    title: string | null;
    note: string | null;
    description: string | "";
    orderRank: number | null;
  }>;
  items: Array<{
    id: string;
    category: string | null;
    name: string | null;
    description: string | "";
    subheading: string | null;
    pricePence: number | null;
    priceLabel: string | null;
    hidePrice: boolean | null;
    isAlcoholic: boolean | null;
    isVegetarian: boolean | null;
    isVegan: boolean | null;
    dietaryReviewStatus: "confirmed" | "needs-review" | null;
    allergens: Array<string> | Array<never>;
    spiceLevel:
      "aromatic" | "gentle" | "hot" | "medium" | "none" | "warm" | null;
    available: boolean | null;
    onlineOrdering: boolean | null;
    featured: boolean | null;
    displayOrder: number | null;
    image: {
      alt: string | null;
      caption: string | null;
      url: string | null;
      dimensions: SanityImageDimensions | null;
    } | null;
  }>;
  page:
    | {
        eyebrow: null;
        headingLineOne: null;
        headingLineTwo: null;
        introduction: null;
        journeyLinkLabel: null;
        manifestEyebrow: null;
        manifestHeading: null;
        manifestIntroduction: null;
        dietaryNotice: null;
        alcoholNotice: null;
        voyageStops: null;
        seo: null;
      }
    | {
        eyebrow: null;
        headingLineOne: null;
        headingLineTwo: null;
        introduction: null;
        journeyLinkLabel: null;
        manifestEyebrow: null;
        manifestHeading: null;
        manifestIntroduction: null;
        dietaryNotice: null;
        alcoholNotice: null;
        voyageStops: null;
        seo: Seo | null;
      }
    | {
        eyebrow: string | null;
        headingLineOne: null;
        headingLineTwo: null;
        introduction: null;
        journeyLinkLabel: null;
        manifestEyebrow: null;
        manifestHeading: null;
        manifestIntroduction: null;
        dietaryNotice: null;
        alcoholNotice: null;
        voyageStops: null;
        seo: null;
      }
    | {
        eyebrow: string | null;
        headingLineOne: null;
        headingLineTwo: null;
        introduction: null;
        journeyLinkLabel: null;
        manifestEyebrow: null;
        manifestHeading: null;
        manifestIntroduction: null;
        dietaryNotice: null;
        alcoholNotice: null;
        voyageStops: null;
        seo: Seo | null;
      }
    | {
        eyebrow: string | null;
        headingLineOne: string | null;
        headingLineTwo: string | null;
        introduction: string | null;
        journeyLinkLabel: string | null;
        manifestEyebrow: string | null;
        manifestHeading: string | null;
        manifestIntroduction: string | null;
        dietaryNotice: string | null;
        alcoholNotice: string | null;
        voyageStops: Array<{
          _key: string;
          itemId: string | null;
          area: string | null;
          region: string | null;
          coordinates: string | null;
          year: string | null;
          course: string | null;
          description: string | null;
          image: {
            alt: string | null;
            url: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        }> | null;
        seo: Seo | null;
      }
    | null;
};

// Source: ../sanity/lib/queries.ts
// Variable: checkoutMenuItemQuery
// Query: *[_type == "menuItem" && (sourceKey == $id || _id == $id)][0] {  "id": coalesce(sourceKey, _id),  "category": category->slug.current,  name,  pricePence,  available,  onlineOrdering,  isAlcoholic}
export type CheckoutMenuItemQueryResult = {
  id: string;
  category: string | null;
  name: string | null;
  pricePence: number | null;
  available: boolean | null;
  onlineOrdering: boolean | null;
  isAlcoholic: boolean | null;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: siteSettingsQuery
// Query: *[_id == "siteSettings"][0] {  restaurantName,  legalName,  shortDescription,  description,  siteUrl,  phone,  email,  reservationEmail,  address,  coordinates,  mapUrl,  openingHours,  socialLinks,  primaryNavigation,  footerNavigation,  announcement,  copyrightText,  defaultSeo,  logo {alt, "url": asset->url},  lightLogo {alt, "url": asset->url},  favicon {alt, "url": asset->url}}
export type SiteSettingsQueryResult =
  | {
      restaurantName: null;
      legalName: null;
      shortDescription: null;
      description: null;
      siteUrl: null;
      phone: null;
      email: null;
      reservationEmail: null;
      address: null;
      coordinates: null;
      mapUrl: null;
      openingHours: null;
      socialLinks: null;
      primaryNavigation: null;
      footerNavigation: null;
      announcement: null;
      copyrightText: null;
      defaultSeo: null;
      logo: null;
      lightLogo: null;
      favicon: null;
    }
  | {
      restaurantName: null;
      legalName: null;
      shortDescription: null;
      description: string | null;
      siteUrl: null;
      phone: null;
      email: null;
      reservationEmail: null;
      address: null;
      coordinates: null;
      mapUrl: null;
      openingHours: null;
      socialLinks: null;
      primaryNavigation: null;
      footerNavigation: null;
      announcement: null;
      copyrightText: null;
      defaultSeo: null;
      logo: null;
      lightLogo: null;
      favicon: null;
    }
  | {
      restaurantName: string | null;
      legalName: string | null;
      shortDescription: string | null;
      description: string | null;
      siteUrl: string | null;
      phone: string | null;
      email: string | null;
      reservationEmail: string | null;
      address: {
        streetAddress?: string;
        locality?: string;
        region?: string;
        postalCode?: string;
        country?: string;
      } | null;
      coordinates: {
        latitude?: number;
        longitude?: number;
      } | null;
      mapUrl: string | null;
      openingHours: Array<{
        days?: string;
        hours?: string;
        _key: string;
      }> | null;
      socialLinks: Array<{
        platform?: string;
        url?: string;
        _key: string;
      }> | null;
      primaryNavigation: Array<
        {
          _key: string;
        } & Link
      > | null;
      footerNavigation: Array<
        {
          _key: string;
        } & Link
      > | null;
      announcement: string | null;
      copyrightText: string | null;
      defaultSeo: Seo | null;
      logo: {
        alt: string | null;
        url: string | null;
      } | null;
      lightLogo: {
        alt: string | null;
        url: string | null;
      } | null;
      favicon: {
        alt: string | null;
        url: string | null;
      } | null;
    }
  | null;

// Source: ../sanity/lib/queries.ts
// Variable: marketingPageQuery
// Query: *[_type == "marketingPage" && pageKey == $pageKey][0] {  pageKey,  title,  eyebrow,  heroHeading,  heroText,  heroImage {alt, caption, "url": asset->url, "dimensions": asset->metadata.dimensions},  heroPrimaryLink,  heroSecondaryLink,  sections[] {    _key,    _type,    internalName,    eyebrow,    heading,    body,    text,    image {alt, caption, "url": asset->url, "dimensions": asset->metadata.dimensions},    secondaryImage {alt, caption, "url": asset->url, "dimensions": asset->metadata.dimensions},    links,    primaryLink,    secondaryLink,    shortLabel,    note,    theme  },  seo}
export type MarketingPageQueryResult = {
  pageKey:
    | "hall"
    | "home"
    | "payments"
    | "restaurant"
    | "story-calicut"
    | "story"
    | null;
  title: string | null;
  eyebrow: string | null;
  heroHeading: string | null;
  heroText: string | null;
  heroImage: {
    alt: string | null;
    caption: string | null;
    url: string | null;
    dimensions: SanityImageDimensions | null;
  } | null;
  heroPrimaryLink: Link | null;
  heroSecondaryLink: Link | null;
  sections: Array<
    | {
        _key: string;
        _type: "callToAction";
        internalName: null;
        eyebrow: string | null;
        heading: string | null;
        body: null;
        text: string | null;
        image: {
          alt: string | null;
          caption: string | null;
          url: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
        secondaryImage: null;
        links: null;
        primaryLink: Link | null;
        secondaryLink: Link | null;
        shortLabel: null;
        note: null;
        theme: null;
      }
    | {
        _key: string;
        _type: "contentSection";
        internalName: string | null;
        eyebrow: string | null;
        heading: string | null;
        body: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        text: null;
        image: {
          alt: string | null;
          caption: string | null;
          url: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
        secondaryImage: {
          alt: string | null;
          caption: string | null;
          url: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
        links: Array<
          {
            _key: string;
          } & Link
        > | null;
        primaryLink: null;
        secondaryLink: null;
        shortLabel: string | null;
        note: string | null;
        theme: "copper" | "dark" | "green" | "light" | null;
      }
  > | null;
  seo: Seo | null;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: faqItemsQuery
// Query: *[_type == "faqItem" && published != false] | order(displayOrder asc) {  question,  answer,  category,  displayOrder}
export type FaqItemsQueryResult = Array<{
  question: string | null;
  answer: string | null;
  category: string | null;
  displayOrder: number | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: testimonialsQuery
// Query: *[_type == "testimonial" && published != false] | order(displayOrder asc) {  quote,  name,  source,  rating,  displayOrder}
export type TestimonialsQueryResult = Array<{
  quote: string | null;
  name: string | null;
  source: string | null;
  rating: number | null;
  displayOrder: number | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: activePromotionsQuery
// Query: *[    _type == "promotion" &&    status == "active" &&    (!defined(startsAt) || startsAt <= now()) &&    (!defined(endsAt) || endsAt >= now())  ] | order(displayOrder asc, startsAt desc, _createdAt desc) {    _id,    title,    badge,    summary,    offerCode,    validityLabel,    startsAt,    endsAt,    showOnHomepage,    terms,    callToAction,    poster {      alt,      caption,      hotspot,      crop,      "url": asset->url,      "dimensions": asset->metadata.dimensions,      "lqip": asset->metadata.lqip    }  }
export type ActivePromotionsQueryResult = Array<{
  _id: string;
  title: string | null;
  badge: string | null;
  summary: string | null;
  offerCode: string | null;
  validityLabel: string | null;
  startsAt: string | null;
  endsAt: string | null;
  showOnHomepage: boolean | null;
  terms: string | null;
  callToAction: Link | null;
  poster: {
    alt: string | null;
    caption: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    url: string | null;
    dimensions: SanityImageDimensions | null;
    lqip: string | null;
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '{\n  "menuItems": *[_type == "menuItem"] | order(category->orderRank asc, displayOrder asc, name asc) {\n    _id,\n    name,\n    "category": category->title,\n    "categorySlug": category->slug.current,\n    pricePence,\n    "available": coalesce(available, true),\n    "onlineOrdering": coalesce(onlineOrdering, true),\n    "featured": coalesce(featured, false),\n    "isAlcoholic": coalesce(isAlcoholic, false),\n    "updatedAt": _updatedAt\n  },\n  "promotions": *[_type == "promotion"] | order(displayOrder asc, _updatedAt desc) {\n    _id,\n    title,\n    "status": coalesce(status, "paused"),\n    "showOnHomepage": coalesce(showOnHomepage, false),\n    startsAt,\n    endsAt,\n    "updatedAt": _updatedAt,\n    poster {alt, "url": asset->url}\n  },\n  "pages": *[_type in ["marketingPage", "legalPage"]] | order(_type asc, pageKey asc) {\n    _id,\n    _type,\n    title,\n    pageKey,\n    "updatedAt": _updatedAt\n  },\n  "categoryCount": count(*[_type == "menuCategory"]),\n  "faqCount": count(*[_type == "faqItem"]),\n  "testimonialCount": count(*[_type == "testimonial"]),\n  "hasMenuPage": defined(*[_id == "menuPage"][0]._id),\n  "hasSiteSettings": defined(*[_id == "siteSettings"][0]._id)\n}': AdminContentOverviewQueryResult;
    '{\n  "categories": *[_type == "menuCategory" && published != false] | order(orderRank asc) {\n    "slug": slug.current,\n    title,\n    "note": coalesce(shortTitle, title),\n    "description": coalesce(description, ""),\n    orderRank\n  },\n  "items": *[_type == "menuItem"] | order(category->orderRank asc, displayOrder asc, name asc) {\n    "id": coalesce(sourceKey, _id),\n    "category": category->slug.current,\n    name,\n    "description": coalesce(description, ""),\n    subheading,\n    pricePence,\n    priceLabel,\n    hidePrice,\n    isAlcoholic,\n    isVegetarian,\n    isVegan,\n    dietaryReviewStatus,\n    "allergens": coalesce(allergens, []),\n    spiceLevel,\n    available,\n    onlineOrdering,\n    featured,\n    displayOrder,\n    image {\n      alt,\n      caption,\n      "url": asset->url,\n      "dimensions": asset->metadata.dimensions\n    }\n  },\n  "page": *[_id == "menuPage"][0] {\n    eyebrow,\n    headingLineOne,\n    headingLineTwo,\n    introduction,\n    journeyLinkLabel,\n    manifestEyebrow,\n    manifestHeading,\n    manifestIntroduction,\n    dietaryNotice,\n    alcoholNotice,\n    voyageStops[] {\n      _key,\n      "itemId": coalesce(dish->sourceKey, dish->_id),\n      "area": coalesce(area, port),\n      region,\n      coordinates,\n      "year": yearLabel,\n      "course": courseLabel,\n      description,\n      image {\n        alt,\n        "url": asset->url,\n        "dimensions": asset->metadata.dimensions\n      }\n    },\n    seo\n  }\n}': MenuContentQueryResult;
    '*[_type == "menuItem" && (sourceKey == $id || _id == $id)][0] {\n  "id": coalesce(sourceKey, _id),\n  "category": category->slug.current,\n  name,\n  pricePence,\n  available,\n  onlineOrdering,\n  isAlcoholic\n}': CheckoutMenuItemQueryResult;
    '*[_id == "siteSettings"][0] {\n  restaurantName,\n  legalName,\n  shortDescription,\n  description,\n  siteUrl,\n  phone,\n  email,\n  reservationEmail,\n  address,\n  coordinates,\n  mapUrl,\n  openingHours,\n  socialLinks,\n  primaryNavigation,\n  footerNavigation,\n  announcement,\n  copyrightText,\n  defaultSeo,\n  logo {alt, "url": asset->url},\n  lightLogo {alt, "url": asset->url},\n  favicon {alt, "url": asset->url}\n}': SiteSettingsQueryResult;
    '*[_type == "marketingPage" && pageKey == $pageKey][0] {\n  pageKey,\n  title,\n  eyebrow,\n  heroHeading,\n  heroText,\n  heroImage {alt, caption, "url": asset->url, "dimensions": asset->metadata.dimensions},\n  heroPrimaryLink,\n  heroSecondaryLink,\n  sections[] {\n    _key,\n    _type,\n    internalName,\n    eyebrow,\n    heading,\n    body,\n    text,\n    image {alt, caption, "url": asset->url, "dimensions": asset->metadata.dimensions},\n    secondaryImage {alt, caption, "url": asset->url, "dimensions": asset->metadata.dimensions},\n    links,\n    primaryLink,\n    secondaryLink,\n    shortLabel,\n    note,\n    theme\n  },\n  seo\n}': MarketingPageQueryResult;
    '*[_type == "faqItem" && published != false] | order(displayOrder asc) {\n  question,\n  answer,\n  category,\n  displayOrder\n}': FaqItemsQueryResult;
    '*[_type == "testimonial" && published != false] | order(displayOrder asc) {\n  quote,\n  name,\n  source,\n  rating,\n  displayOrder\n}': TestimonialsQueryResult;
    '\n  *[\n    _type == "promotion" &&\n    status == "active" &&\n    (!defined(startsAt) || startsAt <= now()) &&\n    (!defined(endsAt) || endsAt >= now())\n  ] | order(displayOrder asc, startsAt desc, _createdAt desc) {\n    _id,\n    title,\n    badge,\n    summary,\n    offerCode,\n    validityLabel,\n    startsAt,\n    endsAt,\n    showOnHomepage,\n    terms,\n    callToAction,\n    poster {\n      alt,\n      caption,\n      hotspot,\n      crop,\n      "url": asset->url,\n      "dimensions": asset->metadata.dimensions,\n      "lqip": asset->metadata.lqip\n    }\n  }\n': ActivePromotionsQueryResult;
  }
}
