import { redirect } from "next/navigation";
import { getAdminSession } from "../../lib/admin-auth";
import { listHallEnquiries } from "../../lib/booking-store";
import { hallEnquiryStatuses } from "../../lib/bookings";
import { adminCan } from "../../lib/admin-permissions";
import { AdminFrame, AdminPageHeader, EmptyState, MetricCard } from "../components/admin-ui";

export const dynamic="force-dynamic";
export default async function HallEnquiriesAdminPage({searchParams}:{searchParams:Promise<{update?:string}>}){const session=await getAdminSession("hall:read");if(!session)redirect("/admin/login");const [items,query]=await Promise.all([listHallEnquiries(),searchParams]);const canWrite=adminCan(session.role,"hall:write");return <AdminFrame active="/admin/hall-enquiries" session={session}><AdminPageHeader eyebrow="Private events" title="Hall enquiries." description="Review requests, contact guests and record the company decision. A request is never treated as confirmed automatically."/>{query.update&&<p className={`adminAlert ${query.update==="success"?"isSuccess":"isError"}`}>{query.update==="success"?"Hall enquiry updated.":"That update was rejected."}</p>}<section className="adminMetrics"><MetricCard label="New requests" value={items.filter(i=>i.status==="new").length} detail="Need first contact" tone={items.some(i=>i.status==="new")?"attention":undefined}/><MetricCard label="In discussion" value={items.filter(i=>i.status==="contacted").length} detail="Contact has started"/><MetricCard label="Approved" value={items.filter(i=>i.status==="approved").length} detail="Accepted by the team"/><MetricCard label="Total enquiries" value={items.length} detail="All recorded requests"/></section><section className="adminPanel"><div className="adminPanelHeading"><div><p>Request register</p><h2>Every hall enquiry</h2></div></div>{!items.length?<EmptyState title="No hall enquiries" detail="Requests from the public hall page will appear here."/>:<div className="adminTableWrap"><table className="adminOrdersTable"><thead><tr><th>Reference</th><th>Preferred date</th><th>Customer</th><th>Plan</th><th>Contact</th><th>Status</th><th>Decision</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><strong>{item.reference}</strong><small>{item.createdAt.slice(0,10)}</small></td><td><strong>{item.preferredDate}</strong><small>{item.preferredTime||"Time flexible"}{item.alternativeDate?` · Alt ${item.alternativeDate}`:""}</small></td><td><strong>{item.name}</strong><small>{item.phone} · {item.email}</small></td><td><strong>{item.occasion||"Private event"}</strong><small>{item.guestCount?`${item.guestCount} guests · `:""}{item.message}</small></td><td><strong>{item.contactPreference}</strong><small>Preferred contact method</small></td><td><span className={`adminStatus hall_${item.status}`}>{item.status}</span></td><td>{canWrite&&<form className="adminInlineUpdate" action={`/api/admin/hall-enquiries/${item.id}`} method="post"><input type="hidden" name="csrf" value={session.csrfToken}/><select name="status" defaultValue={item.status}>{hallEnquiryStatuses.map(status=><option key={status}>{status}</option>)}</select><input name="adminNotes" defaultValue={item.adminNotes} placeholder="Call outcome or staff note" maxLength={1000}/><button>Save</button></form>}</td></tr>)}</tbody></table></div>}</section></AdminFrame>}
