import type { HallEnquiry, TableReservation } from "../bookings";
import type { OrderRecord } from "../orders";
import { ownerEmail, sendBrevoEmail } from "./brevo";

const esc=(value:unknown)=>String(value??"").replace(/[&<>"']/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]!));
const money=(pence:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(pence/100);
const frame=(title:string,body:string)=>`<!doctype html><html><body style="margin:0;background:#f4efe4;color:#10201c;font-family:Arial,sans-serif"><div style="max-width:640px;margin:auto;padding:36px 24px"><p style="color:#9a6a31;font-size:12px;letter-spacing:2px;text-transform:uppercase">Malabar Coast · Holytown</p><h1 style="font-family:Georgia,serif;font-weight:400">${esc(title)}</h1>${body}<p style="margin-top:32px;padding-top:20px;border-top:1px solid #d4c8b2;color:#6c716e;font-size:13px">33 Main Street, Holytown, North Lanarkshire, ML1 4TH</p></div></body></html>`;
const row=(label:string,value:unknown)=>`<p style="margin:8px 0"><strong>${esc(label)}:</strong> ${esc(value)}</p>`;

export async function notifyPaidOrder(order:OrderRecord){const items=order.lines.map(line=>`${line.quantity}× ${line.name} — ${money(line.lineTotalPence)}`).join("\n");const htmlItems=order.lines.map(line=>`<li>${esc(line.quantity)}× ${esc(line.name)} — ${esc(money(line.lineTotalPence))}</li>`).join("");await Promise.allSettled([
  sendBrevoEmail({eventKey:`order:${order.id}:paid:customer`,category:"paid_order_customer",to:{email:order.customer.email,name:order.customer.name},subject:`Payment received · Order ${order.id.slice(-8).toUpperCase()}`,html:frame("Your order is paid and received.",row("Order",order.id.slice(-8).toUpperCase())+row("Payment","Paid securely with Stripe")+row("Total",money(order.totalPence))+row("Requested",order.requestedTime)+`<ul>${htmlItems}</ul>`),text:`Your Malabar Coast order is paid.\nOrder: ${order.id}\nPayment: Stripe paid\nTotal: ${money(order.totalPence)}\nRequested: ${order.requestedTime}\n${items}`}),
  sendBrevoEmail({eventKey:`order:${order.id}:paid:owner`,category:"paid_order_owner",to:{email:ownerEmail(),name:"Malabar Coast team"},subject:`New paid order · ${money(order.totalPence)} · ${order.customer.name}`,html:frame("A paid order has arrived.",row("Customer",order.customer.name)+row("Phone",order.customer.phone)+row("Email",order.customer.email)+row("Fulfilment",order.fulfilment)+row("Requested",order.requestedTime)+row("Total",money(order.totalPence))+`<ul>${htmlItems}</ul>`),text:`New paid order ${order.id}\n${order.customer.name} · ${order.customer.phone}\n${order.fulfilment} at ${order.requestedTime}\n${money(order.totalPence)}\n${items}`}),
]);}

export async function notifyReservation(reservation:TableReservation){const details=row("Reference",reservation.reference)+row("Date",reservation.bookingDate)+row("Time",`${reservation.startTime}–${reservation.endTime}`)+row("Guests",reservation.partySize);await Promise.allSettled([
  sendBrevoEmail({eventKey:`reservation:${reservation.id}:confirmed:customer`,category:"reservation_customer",to:{email:reservation.email,name:reservation.name},subject:`Table confirmed · ${reservation.bookingDate} at ${reservation.startTime}`,html:frame("Your table is confirmed.",details+row("Name",reservation.name)+row("Dietary requirements",reservation.dietaryRequirements||"None provided")),text:`Your table is confirmed.\n${reservation.reference}\n${reservation.bookingDate} ${reservation.startTime}-${reservation.endTime}\n${reservation.partySize} guests.`}),
  sendBrevoEmail({eventKey:`reservation:${reservation.id}:confirmed:owner`,category:"reservation_owner",to:{email:ownerEmail(),name:"Malabar Coast team"},subject:`New table · ${reservation.partySize} guests · ${reservation.bookingDate} ${reservation.startTime}`,html:frame("A table has been booked.",details+row("Customer",reservation.name)+row("Phone",reservation.phone)+row("Email",reservation.email)+row("Dietary",reservation.dietaryRequirements||"None provided")+row("Accessibility",reservation.accessibilityNeeds||"None provided")+row("Notes",reservation.notes||"None")),text:`New table ${reservation.reference}\n${reservation.name} · ${reservation.phone}\n${reservation.bookingDate} ${reservation.startTime}\n${reservation.partySize} guests.`}),
]);}

export async function notifyHallEnquiry(enquiry:HallEnquiry){const details=row("Reference",enquiry.reference)+row("Preferred date",enquiry.preferredDate)+row("Preferred time",enquiry.preferredTime||"Flexible")+row("Estimated guests",enquiry.guestCount||"Not provided");await Promise.allSettled([
  sendBrevoEmail({eventKey:`hall:${enquiry.id}:new:customer`,category:"hall_customer",to:{email:enquiry.email,name:enquiry.name},subject:`Hall enquiry received · ${enquiry.reference}`,html:frame("We have received your hall enquiry.",details+`<p>This is a request, not a confirmed booking. Our team will review it and contact you.</p>`),text:`Hall enquiry received. ${enquiry.reference}. This is not yet confirmed; our team will contact you.`}),
  sendBrevoEmail({eventKey:`hall:${enquiry.id}:new:owner`,category:"hall_owner",to:{email:ownerEmail(),name:"Malabar Coast team"},subject:`New hall enquiry · ${enquiry.preferredDate} · ${enquiry.name}`,html:frame("A hall request needs review.",details+row("Customer",enquiry.name)+row("Phone",enquiry.phone)+row("Email",enquiry.email)+row("Occasion",enquiry.occasion||"Not provided")+row("Message",enquiry.message)),text:`New hall enquiry ${enquiry.reference}\n${enquiry.name} · ${enquiry.phone}\n${enquiry.preferredDate}\n${enquiry.message}`}),
]);}

export async function notifyHallDecision(enquiry:HallEnquiry){if(!["approved","declined"].includes(enquiry.status))return;await sendBrevoEmail({eventKey:`hall:${enquiry.id}:${enquiry.status}:customer`,category:"hall_decision",to:{email:enquiry.email,name:enquiry.name},subject:`Hall enquiry update · ${enquiry.reference}`,html:frame(enquiry.status==="approved"?"Your hall enquiry has been approved for the next step.":"An update on your hall enquiry.",row("Reference",enquiry.reference)+row("Status",enquiry.status)+`<p>${enquiry.status==="approved"?"The team will contact you to finalise details. Approval is not a payment receipt or final event contract.":"The requested plan cannot be accepted at this time. Please contact the restaurant if you would like to discuss alternatives."}</p>`),text:`Hall enquiry ${enquiry.reference}: ${enquiry.status}.`});}
