import { createHash, randomBytes } from "node:crypto";
import { existsSync } from "node:fs";
import { loadEnvFile } from "node:process";
import { applyPaymentEvent, createCheckoutOrderAtomic, isDurableOrderStorageConfigured } from "../app/lib/order-store";
import type { OrderRecord } from "../app/lib/orders";
import { publishPaymentCompletionEvent } from "../app/lib/publishEvent";

// Shell-provided variables retain precedence. Prefer Next.js's local env file,
// then fall back to a plain .env when running outside the development setup.
const envFile = existsSync(".env.local") ? ".env.local" : ".env";
if (existsSync(envFile)) loadEnvFile(envFile);

function digest(value: string) {
  return createHash("sha256").update(value).digest("hex");
}

function restaurantTimeTomorrow() {
  const tomorrow = new Date(Date.now() + 24 * 60 * 60_000);
  const parts = new Intl.DateTimeFormat("en-GB", {
    timeZone: "Europe/London",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    hourCycle: "h23",
  }).formatToParts(tomorrow).reduce<Record<string, string>>((result, part) => {
    if (part.type !== "literal") result[part.type] = part.value;
    return result;
  }, {});
  return `${parts.year}-${parts.month}-${parts.day}T${parts.hour}:${parts.minute}`;
}

async function main() {
  const url = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serverKey = process.env.SUPABASE_SECRET_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !serverKey || !isDurableOrderStorageConfigured()) {
    throw new Error(
      "Set SUPABASE_URL and SUPABASE_SECRET_KEY (or SUPABASE_SERVICE_ROLE_KEY) before running this script.",
    );
  }

  const unique = randomBytes(24).toString("base64url");
  const orderId = `ord_${unique}`;
  const eventId = `realtime_test_${randomBytes(16).toString("hex")}`;
  const providerReference = `pi_test_${randomBytes(12).toString("hex")}`;
  const now = new Date().toISOString();

  const order: OrderRecord = {
    id: orderId,
    createdAt: now,
    updatedAt: now,
    status: "pending_payment",
    paymentStatus: "pending",
    provider: "stripe",
    idempotencyKeyHash: digest(`realtime-test-idempotency:${unique}`),
    requestFingerprint: digest(`realtime-test-request:${unique}`),
    customer: {
      name: "Realtime Test Customer",
      email: "realtime-test@example.invalid",
      phone: "+44 7700 900000",
    },
    fulfilment: "collection",
    requestedTime: restaurantTimeTomorrow(),
    orderNote: "Generated by pnpm test:realtime; safe to remove after testing.",
    lines: [{
      menuItemId: "realtime-test-item",
      name: "Realtime Test Order",
      unitPricePence: 1595,
      quantity: 1,
      note: "Automated realtime test",
      lineTotalPence: 1595,
    }],
    subtotalPence: 1595,
    deliveryFeePence: 0,
    totalPence: 1595,
    currency: "GBP",
    statusHistory: [{ status: "pending_payment", at: now, actor: "system" }],
  };

  const created = await createCheckoutOrderAtomic(order);
  if (created.result !== "created") {
    throw new Error(`Expected a new test order, received: ${created.result}`);
  }

  const paymentApplied = await applyPaymentEvent({
    provider: "stripe",
    eventId,
    orderId,
    paymentStatus: "paid",
    outcome: "realtime_test_paid",
    providerReference,
    amountPence: order.totalPence,
    currency: order.currency,
  });
  if (!paymentApplied) {
    throw new Error(`The test order ${orderId} was created, but its paid event was rejected.`);
  }

  await publishPaymentCompletionEvent(orderId);

  console.log(`Created paid test order: ${orderId}`);
  console.log("Published: admin-orders / orders-changed");
  console.log("The order should now appear in the open admin dashboard in real time.");
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
